#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 14 18:04:32 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}